# EAV Planning Template Configuration - 100% Required Tasks
# All durations are in business days (Monday-Friday)
# Window Duration = Calendar time from start to when next task can begin

metadata:
  version: "1.0"
  description: "Core EAV video production workflow - 100% required tasks only"
  created: "2025-01-09"
  working_hours_per_day: 7.5

# GLOBAL SCHEDULING SETTINGS
scheduling:
  business_days_only: true
  weekend_handling: "skip"  # Don't count Saturday/Sunday
  holiday_calendar: null    # Future enhancement
  
  # Smart start day preferences
  start_day_preferences:
    client_reviews: "monday"     # Start client reviews on Monday
    filming: "tuesday"           # Avoid Monday filming rushes
    internal_tasks: "any_weekday"
    delivery: "thursday"         # Allow Friday buffer for issues

  # Scheduling Principles
  calculation_method: "backward_from_due_date"
  execution_order: "forward_from_setup"
  principle: |
    Tasks are calculated backward from P11 (Project Due Date) to determine
    their latest allowable start dates. However, tasks execute forward in
    logical sequence starting from P1-Setup. Each task has a window duration
    that creates a from_date (start) and to_date (end). The predecessor's
    to_date becomes the successor's from_date in backward calculation.

# PROJECT-LEVEL TASKS (Always Required)
project_tasks:
  p1_setup:
    name: "P1-Setup"
    duration: 3
    duration_type: "business_days"
    level: "project"
    variants: []
    dependencies: ["client_agreement"]
    creates: ["p2_booking_recce", "p4_branding", "p8_specs"]
    description: "Project foundation setup - SmartSuite records, LucidLink folders, team assignment"
    
  p2_booking_recce:
    name: "P2-Booking"
    duration: 5
    buffer_days: 14
    duration_type: "business_days"
    level: "project"
    variants: ["recce"]
    dependencies: ["p1_setup"]
    creates: ["p3_attendance_recce"]
    description: "Schedule reconnaissance visit with client"
    execution_note: "Must follow P1 chronologically, calculated backward from P3"
    
  p2_booking_shoot:
    name: "P2-Booking"
    duration: 10
    buffer_days: 14
    duration_type: "business_days"
    level: "project"
    variants: ["shoot"]
    dependencies: ["p1_setup"]
    creates: ["p9_filming"]
    description: "Schedule main filming dates after recce"
    execution_note: "Must follow P3 chronologically, calculated backward from P9"
    
  p3_attendance_recce:
    name: "P3-Attendance"
    duration: 1
    duration_type: "business_days"
    level: "project"
    variants: ["recce"]
    dependencies: ["p2_booking_recce"]
    description: "Attend reconnaissance visit"
    
  p4_branding:
    name: "P4-Branding Collection"
    duration: 10
    duration_type: "business_days"
    level: "project"
    variants: []
    dependencies: ["p1_setup"]
    parallel: true  # Can run alongside other P tasks
    description: "Collect client branding assets and brand guidelines"
    
  p5_music:
    name: "P5-Music Collection"
    duration: 5
    duration_type: "business_days"
    level: "project"
    variants: []
    dependencies: ["p4_branding"]
    description: "Source appropriate music for project"
    
  p6_mogrt_check:
    name: "P6-MOGRT Check"
    duration: 5
    duration_type: "business_days"
    level: "project"
    variants: []
    dependencies: ["p4_branding"]
    parallel: true  # Can run with P5
    description: "Check existing motion graphics templates"
    
  p8_specs:
    name: "P8-Spec Collection"
    duration: 5
    duration_type: "business_days"
    level: "project"
    variants: []
    dependencies: ["p1_setup"]
    parallel: true  # Can run alongside other P tasks
    description: "Collect development specifications and analyze content requirements"
    
  p9_filming_shoot:
    name: "P9-Filming"
    duration_formula: "ROUNDUP(0.15 * (new_vids + amend_vids), 0.5)"
    duration_min: 1
    duration_type: "business_days"
    level: "project"
    variants: ["shoot"]
    dependencies: ["p2_booking_shoot", "v5_scenes_complete"]
    creates: ["p10_ingestion"]
    description: "Execute filming according to scene plans"
    resource_days: "0.15 per video"
    execution_note: "Critical convergence point - must follow both booking and scene planning"
    
  p10_ingestion:
    name: "P10-Media Ingestion"
    duration: 3
    duration_type: "business_days"
    level: "project"
    variants: []
    dependencies: ["p9_filming"]
    description: "Import media, organize footage, create proxies"
    
  p11_delivery:
    name: "P11-Client Delivery"
    duration: 3
    duration_type: "business_days"
    level: "project"
    variants: []
    dependencies: ["v10_video_revision_client"]
    due_date_rule: "project_due_date"
    description: "Export final formats, upload to platforms, generate delivery docs - after all video revision buffers"
    
  p12_completion:
    name: "P12-Completion & Invoicing"
    duration: 5
    duration_type: "business_days"
    level: "project"
    variants: []
    dependencies: ["p11_delivery"]
    due_date_rule: "project_due_date + 7_business_days"
    description: "Finalize invoicing and complete project closure"

# VIDEO-LEVEL TASKS (Batch Allocated to New + Amend Videos)
video_tasks:
  v1_manuals:
    name: "V1-User Manual Collection"
    duration: 5
    duration_type: "business_days"
    level: "video"
    variants: []
    batch_allocate: ["new", "amend"]
    conditional: "user_manual_checkbox = true"
    dependencies: ["p8_specs"]
    description: "Collect appliance manuals and extract technical specifications"
    
  v2_script_creation:
    name: "V2-Script Creation"
    duration: 5
    duration_type: "business_days"
    level: "video"
    variants: []
    batch_allocate: ["new", "amend"]
    dependencies: ["p8_specs", "v1_manuals_if_required"]
    description: "Create scripts from specifications or manuals"
    
  v3_script_review_internal:
    name: "V3-Script Review"
    duration: 3
    duration_type: "business_days"
    level: "video"
    variants: ["internal"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v2_script_creation"]
    creates: ["v4_script_revision_internal"]
    description: "Internal quality review of scripts - sequential progression to internal revision buffer"
    
  v3_script_review_client:
    name: "V3-Script Review"
    duration: 5
    duration_type: "business_days"
    level: "video"
    variants: ["client"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v4_script_revision_internal"]
    creates: ["v4_script_revision_client"]
    auto_approve_days: 7
    preferred_start: "monday"
    description: "Client approval review of scripts - sequential progression from internal revision buffer"
    
  v4_script_revision_internal:
    name: "V4-Script Revision"
    duration: 3
    duration_type: "business_days"
    level: "video"
    variants: ["internal"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v3_script_review_internal"]
    creates: ["v3_script_review_client"]
    resource_formula: "0.08 * (new_vids + amend_vids) * 0.25"
    conditional: true
    description: "Buffer window for script revisions - sequential progression to client review"
    
  v4_script_revision_client:
    name: "V4-Script Revision"
    duration: 2
    duration_type: "business_days"
    level: "video"
    variants: ["client"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v3_script_review_client"]
    creates: ["v5_scenes", "v6_vo_generation"]
    resource_formula: "0.15 * (new_vids + amend_vids) * 0.25"
    conditional: true
    description: "Buffer window for script revisions - sequential progression to scene planning and VO"
    
  v4_script_revision_internal:
    name: "V4-Script Revision"
    duration: 3
    duration_type: "business_days"
    level: "video"
    variants: ["internal"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v3_script_review_internal_changes_needed"]
    resource_formula: "0.08 * (new_vids + amend_vids) * 0.25"
    conditional: true
    description: "Buffer window for script revisions based on internal feedback"
    
  v4_script_revision_client:
    name: "V4-Script Revision"
    duration: 2
    duration_type: "business_days"
    level: "video"
    variants: ["client"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v3_script_review_client_changes_needed"]
    resource_formula: "0.15 * (new_vids + amend_vids) * 0.25"
    conditional: true
    description: "Buffer window for script revisions based on client feedback"
    
  v5_scenes:
    name: "V5-Scene Planning"
    duration: 5
    duration_type: "business_days"
    level: "video"
    variants: []
    batch_allocate: ["new", "amend"]
    dependencies: ["v4_script_revision_client"]
    description: "Create detailed scene plans and prepare shot requirements - after client revision buffer"
    
  v6_vo_generation:
    name: "V6-VO Generation"
    duration: 5
    duration_type: "business_days"
    level: "video"
    variants: []
    batch_allocate: ["new", "amend"]
    dependencies: ["v4_script_revision_client"]
    parallel: true  # Can run with V5
    description: "Generate AI voiceover from approved scripts - after client revision buffer"
    
  v7_edit_prep:
    name: "V7-Edit Prep"
    duration: 3
    duration_type: "business_days"
    level: "video"
    variants: []
    batch_allocate: ["new", "amend"]
    dependencies: ["p10_ingestion", "assets_ready", "v6_vo_generation"]
    description: "Prepare edit package and organize assets for editing"
    
  v8_video_edit_quoting:
    name: "V8-Video Edit"
    duration: 3
    duration_type: "business_days"
    level: "video"
    variants: ["quoting"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v7_edit_prep"]
    description: "Hour estimation negotiation between PM and editor"
    
  v8_video_edit:
    name: "V8-Video Edit"
    duration_formula: "ROUNDUP(0.25 * (new_vids + amend_vids), 0.5)"
    duration_min: 1
    buffer_days: 7
    duration_type: "business_days"
    level: "video"
    variants: ["editing", "grading"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v8_video_edit_quoting_approved"]
    description: "Assemble video, sync audio, add graphics"
    resource_days: "0.25 per video, rounded to half-day"
    
  v9_video_review_internal:
    name: "V9-Video Review"
    duration: 3
    duration_type: "business_days"
    level: "video"
    variants: ["internal"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v8_video_edit"]
    creates: ["v10_video_revision_internal"]
    description: "Internal quality assurance review - sequential progression to internal revision buffer"
    
  v9_video_review_client:
    name: "V9-Video Review"
    duration: 5
    duration_type: "business_days"
    level: "video"
    variants: ["client"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v10_video_revision_internal"]
    creates: ["v10_video_revision_client"]
    auto_approve_days: 7
    preferred_start: "monday"
    description: "Client approval review via Frame.io - sequential progression from internal revision buffer"

  # Buffer tasks for revision cycles
  v10_video_revision_internal:
    name: "V10-Video Revision"
    duration: 2
    duration_type: "business_days"
    level: "video"
    variants: ["internal"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v9_video_review_internal"]
    creates: ["v9_video_review_client"]
    resource_formula: "0.15 * (new_vids + amend_vids) * 0.25"
    conditional: true
    description: "Buffer window for internal revisions - sequential progression to client review"
    
  v10_video_revision_client:
    name: "V10-Video Revision"
    duration: 2
    duration_type: "business_days"
    level: "video"
    variants: ["client"]
    batch_allocate: ["new", "amend"]
    dependencies: ["v9_video_review_client"]
    creates: ["p11_delivery"]
    resource_formula: "0.15 * (new_vids + amend_vids) * 0.25"
    conditional: true
    description: "Buffer window for client revisions - sequential progression to final delivery"

# SPECIAL WORKFLOWS
special_tasks:
  p7_mogrt_creation:
    name: "P7-MOGRT Creation"
    duration: 3
    duration_type: "business_days"
    level: "project"
    variants: []
    dependencies: ["p6_mogrt_check"]
    conditional: "mogrt_required = true"
    resource_days: 0.25
    description: "Create motion graphics template when not available"
  v9_video_review_reuse:
    name: "V9-Video Review"
    duration: 10
    duration_type: "business_days"
    level: "video"
    variants: ["reuse"]
    batch_allocate: ["reuse"]
    dependencies: ["p1_setup"]
    timing: "day_3_to_5"
    auto_approve_days: 7
    preferred_start: "monday"
    description: |
      REUSE VIDEO WORKFLOW:
      1. Locate existing videos in library
      2. Copy to project folder
      3. Upload to Frame.io for client review
      4. If approved → skip to delivery prep
      5. If changes needed → manually convert to new/amend workflow

# CALCULATION RULES
calculation_rules:
  batch_scaling: "per_batch"  # Tasks scale per batch, not per individual video
  
  rounding_rules:
    filming: "round_up_to_day"
    editing: "round_up_to_half_day" 
    standard: "round_up_to_day"
    
  duration_formulas:
    # Formula variables available: new_vids, amend_vids, reuse_vids, total_vids
    supported_functions: ["ROUNDUP", "ROUNDDOWN", "MAX", "MIN", "CEIL", "FLOOR"]
    
  resource_calculations:
    # Base resource estimates (in days per task/video)
    project_admin: 0.15  # Most P-level tasks
    video_admin: 0.05   # V1 user manual collection 
    script_creation: 0.15  # V2
    scene_planning: 0.15   # V5
    vo_generation: 0.08    # V6
    edit_prep: 0.08        # V7
    video_edit: 0.25       # V8 (per video)
    internal_review: 0.08  # V9
    
  buffer_strategies:
    booking_buffer: 14     # days added to P2 booking tasks
    client_review_window: 5  # days for client approvals
    auto_approve_days: 7     # days before auto-approval
    revision_probability: 0.5  # 50% chance of revisions needed

# DEPENDENCY DEFINITIONS
dependencies:
  # Cross-stream convergence points
  assets_ready: 
    requires_all: ["p4_branding_complete", "p5_music_complete", "p6_mogrt_check_complete"]
  
  all_videos_approved:
    requires_all: ["v10_video_revision_client_complete"]
    scope: "all_new_amend_videos"
    note: "Changed to V10 client revision completion for sequential flow"
  
  v1_manuals_if_required:
    condition: "IF user_manual_checkbox = true THEN v1_manuals_complete ELSE p8_specs_complete"

# SMARTSUITE FIELD MAPPING
smartsuite_mapping:
  table_id: "68a8ffac490e5496953e5b1c"  # Tasks table
  
  field_mapping:
    task_code: "task_code"
    task_variant: "task_variant" 
    batch_allocation: "batch_alloc"
    due_date: "due_date"
    project_link: "project_id"
    status: "taskstatus"
    estimated_hours: "estimated_hours"
    confirmed_hours: "confirmed_h"
    actual_hours: "actual_hours"
    priority: "priority"
    assigned_to: "assigned_to"
    # THREE-FIELD MODEL:
    due_date: "due_date"           # Simple deadline (My Work overview)
    window_constraints: "duration"  # When work CAN happen (hard boundaries)
    resource_allocation: "rsrc_alloc" # Visual resource booking
    # Lookup fields for video counts
    new_vids: "sac1cc3284"       # New vids count
    amend_vids: "s0a1f5ad8f"     # Amend vids count 
    reuse_vids: "s4e387c8f5"     # Reuse vids count
    project_due_date: "s9cb92c387" # Project due date
    
  default_values:
    status: "to_do"
    priority: "normal"
    task_level: "project_level"  # or "video_level"
    
  # Field type definitions:
  field_types:
    due_date: "duedatefield"      # Simple deadline
    duration: "duedatefield"      # Window constraints 
    rsrc_alloc: "daterangefield"  # Resource allocation

# VARIANT DEFINITIONS
variants:
  # All possible task variants with descriptions
  reuse: 
    label: "(Reuse)"
    color: "#CDEECE"
    description: "Early assessment of existing content for reuse"
    
  recce:
    label: "(Recce)" 
    color: "#10B981"
    description: "Site reconnaissance visits"
    
  shoot:
    label: "(Shoot)"
    color: "#3B82F6"
    description: "Main filming coordination"
    
  pickups:
    label: "(Pickups)"
    color: "#8B5CF6"  
    description: "Additional filming for missed content"
    
  internal:
    label: "(Internal)"
    color: "#F59E0B"
    description: "Internal quality reviews"
    
  client:
    label: "(Client)"
    color: "#06B6D4"
    description: "Client approval processes"
    
  quoting:
    label: "(Quoting)"
    color: "#00B2A8"
    description: "Hour estimation negotiation"
    
  editing:
    label: "(Editing)"
    color: "#EC4899" 
    description: "Video assembly work"
    
  grading:
    label: "(Grading)"
    color: "#9333EA"
    description: "Color correction work"

# STATUS WORKFLOW
status_workflow:
  # SmartSuite status progression
  task_statuses:
    - "to_do"
    - "in_progress" 
    - "internal_review"
    - "client_review"
    - "changes_needed"
    - "complete"
    
  auto_progression_rules:
    client_review_timeout: 7  # business days
    auto_approve_to: "complete"
    
# BUSINESS RULES
business_rules:
  # Project completion definition
  project_complete_when: "all_videos_approved AND p11_delivery_complete"
  project_invoiceable_when: "p12_completion_complete"
  
  # Video type handling
  video_types:
    new: "Full production pipeline required"
    amend: "Full production pipeline with modifications"  
    reuse: "Early review, skip production if approved"
    
  # Batch allocation rules
  batch_allocation:
    max_videos_per_batch: null  # No limit
    separate_batches_by: []     # All videos in single batch per task
