# SmartSuite Clients Table Field Mappings
# SOLUTION 1: EAV Projects (68b6d66b33630eb365ae54cb)
# TABLE 2: Clients (68a8ff34dc58deda12a3bc02)

tableName: clients
tableId: 68a8ff34dc58deda12a3bc02
solutionId: 68b6d66b33630eb365ae54cb

# Field mappings (human name → actual API slug)
fields:
  # Core Client Fields
  clientNumber: autonumber                # Client # - Auto: C001, C002...
  title: title                           # Client Name - Record Title
  clientNameFull: client_name_actual      # Client Name (Full)
  clientType: client_type                 # Client Type - Single Select
  
  # Contact Information
  phone: phone                           # Phone
  email: email                           # Email
  website: website                       # Website
  address: address                       # Address
  primaryContact: primary_contact         # Primary Contact
  contactTitle: contact_title            # Contact Title
  
  # Account Management
  acctManager: acct_manager              # Acct Manager - Members
  industry: industry                     # Industry - Single Select
  companySize: company_size              # Company Size - Single Select
  annualRevenue: annual_revenue          # Annual Revenue - Currency
  
  # Notes & Status
  notes: notes                           # Notes - Rich Text
  status: status                         # Status - Single Select
  
  # Linked Records
  projects: s1a6m83s                     # Projects - Links to Projects table
  
  # System Fields
  firstCreated: first_created            # First Created - Created Time
  lastUpdated: last_updated              # Last Updated - Updated Time
  followedBy: followed_by                # Followed By - User Field
  openComments: comments_count           # Open Comments - Comments Count

# Single Select Options
clientTypeOptions:
  - Client
  - Prospect
  - Partner
  - Past
  - Supplier

industryOptions:
  - Property Development
  - Housing Association
  - Construction
  - Agency
  - Other

companySizeOptions:
  - 1-10
  - 11-50
  - 51-200
  - 201-1000
  - 1000+