# SmartSuite Issue Log Table Field Mappings
# SOLUTION 3: EAV System (68ac236dc90313c20428b15d)
# TABLE 9: Issue Log (68ac236dc90313c20428b15f)

tableName: issue-log
tableId: 68ac236dc90313c20428b15f
solutionId: 68ac236dc90313c20428b15d

# Field mappings (human name → actual API slug)
fields:
  # Core Issue Fields
  issueId: autonumber                    # Issue ID - Autonumber (#01, #02...)
  title: title                           # Issue Title - Record Title
  description: description               # Description - Rich Text
  
  # Assignment & Reporting
  assignedTo: assigned_to                # Assigned To - Members
  reporter: reporter001                  # Reporter - Members
  dateReported: date_rep01               # Date Reported
  
  # Project Relationship
  relatedProject: projectlnk             # Related Project - Linked Record (Optional)
  
  # Status & Timeline
  status: status                         # Status - Status Field
  dueDate: due_date                      # Due Date - Due Date (linked to Status)
  
  # Categorization & Priority
  priority: priority                     # Priority - Single Select
  type: op_type                          # Type - Single Select
  priority1: op_priority                 # Priority 1 - Single Select (with weights)
  
  # Issue Details
  stepsToReproduce: steps_repr           # Steps to Reproduce - Rich Text
  expectedBehavior: expected01           # Expected Behavior - Rich Text
  actualBehavior: actual0001             # Actual Behavior - Rich Text
  workaround: workaround                 # Workaround - Rich Text
  
  # System Impact
  affectedSystems: op_affected_systems   # Affected Systems - Multi Select
  impactLevel: op_impact_level           # Impact Level - Single Select
  
  # Resolution
  actionItems: op_action_items           # Action Items - Text
  solutionNotes: op_solution_notes       # Solution Notes - Rich Text
  dateResolved: op_date_resolved         # Date Resolved
  
  # Attachments
  attachments: attachment                # Attachments - File
  
  # System Fields
  firstCreated: first_created            # First Created - Created Time
  lastUpdated: last_updated              # Last Updated - Updated Time
  followedBy: followed_by                # Followed By - User Field
  openComments: comments_count           # Open Comments - Comments Count

# Status Options
statusOptions:
  - Open
  - In Progress
  - Testing
  - Resolved
  - Closed
  - Deferred

# Priority Options
priorityOptions:
  - Urgent
  - High
  - Normal
  - Low

# Type Options
typeOptions:
  - Technical Issue
  - Process Gap
  - System Enhancement
  - Workflow Optimization
  - Bug Fix
  - Feature Request

# Priority 1 Options (with weights)
priority1Options:
  - Urgent (Weight: 5)
  - Critical (Weight: 4)
  - High (Weight: 3)
  - Normal (Weight: 2)
  - Low (Weight: 1)

# Affected Systems Options
affectedSystemsOptions:
  - SmartSuite
  - LucidLink
  - EAV Operations
  - Adobe Premiere
  - OneDrive
  - MCP Server
  - Other

# Impact Level Options
impactLevelOptions:
  - Project Blocking
  - Workflow Impeding
  - Minor Inconvenience
  - Enhancement