# SmartSuite Planning Table Field Mappings
# SOLUTION 1: EAV Projects (68b6d66b33630eb365ae54cb)
# TABLE: Planning (68bace6c51dce2f0d0f5073b)
# Created: 2025-09-07
# Note: This table replaced the deleted Videos table in EAV Projects

tableName: planning
tableId: 68bace6c51dce2f0d0f5073b
solutionId: 68b6d66b33630eb365ae54cb

# Field mappings (human name → actual API slug)
fields:
  # Core Planning Fields
  title: title                          # Title - Record Title
  autoNumber: autonumber                 # Auto Number - Prefix: "PLN", Leading zeros: 3
  description: description               # Description - Rich Text
  
  # Project Relationships
  project: proj_link1                    # Project - Linked Record to Projects table
  projectCode: sf83f1c32b               # Project Code - Lookup from Project → EAV Code
  client: s2ce8ff9bd                    # Client - Lookup from Project → Client
  pcDate: s0602f2bc7                    # PC Date - Lookup from Project → PC Date
  projectDueDate: s40d5bec0d            # Due Date (Projects) - Lookup from Project → Due Date
  
  # Planning Management
  phase: phase_sel1                     # Phase - Single Select
  planningPeriod: due_date              # Planning Period - Due Date Field
  status: status                        # Status - Status Field
  priority: priority                    # Priority - Single Select
  
  # Timeline Fields
  actualStartDate: actual_st1           # Actual Start Date - Date
  actualEndDate: actual_en1             # Actual End Date - Date
  durationOverrideDays: duration_o      # Duration Override (Days) - Number
  bufferDays: buffer_day                # Buffer Days - Number
  
  # Content
  planningNotes: notes_pln1             # Planning Notes - Rich Text Area
  videoCount: video_cnt1                # Video Count - Text
  
  # Assignment
  assignedTo: assigned_to               # Assigned To - User Field
  
  # Dependencies
  dependency: dependency                # Dependency - Dependency Field
  makeDependencies: s3f49ae6f0         # Make dependencies - Button Field
  
  # System Fields
  firstCreated: first_created           # First Created - Created Time
  lastUpdated: last_updated             # Last Updated - Updated Time
  followedBy: followed_by               # Followed by - User Field
  openComments: comments_count          # Open Comments - Comments Count

# Phase Options (Planning phases)
phaseOptions:
  - Preparation
  - Script/Content
  - VO Generation
  - Scene Planning
  - Filming
  - Editing
  - Revisions
  - Delivery

# Status Options
statusOptions:
  - Not Started
  - In Progress
  - On Hold
  - At Risk
  - Completed
  - Cancelled

# Priority Options
priorityOptions:
  - Critical
  - High
  - Normal
  - Low

# NOTES:
# - This table replaced the old Videos table (68a8ff7a73b82c2f467b8191) which was deleted
# - Used for project phase planning and resource allocation
# - Total of 25 fields (21 user + 4 system)
# - Many fields have '1' suffix in their slugs (proj_link1, phase_sel1, actual_st1)
# - All slugs verified against actual SmartSuite API response 2025-09-07
