# SmartSuite Schedule Table Field Mappings
# SOLUTION 2: EAV Operations (68a8eedc2271ce265ebdae8f)
# TABLE 7: Schedule (68a8ffb767da02533af2bc9c)

tableName: schedule
tableId: 68a8ffb767da02533af2bc9c
solutionId: 68a8eedc2271ce265ebdae8f

# Field mappings (human name → actual API slug)
fields:
  # Core Booking Fields
  bookingId: autonumber                  # Booking ID - Autonumber (BK001, BK002...)
  title: title                           # Booking Title - Record Title
  bookingType: booking_type              # Booking Type - Single Select
  bookingStatus: booking_status          # Booking Status - Single Select
  holdRank: hold_rank                    # Hold Rank - Single Select
  readinessStatus: readiness_status      # Readiness Status - Single Select
  
  # Project Relationship
  project: project_id                    # Project - Linked Record
  projectCode: project_code              # Project Code - Lookup
  
  # Schedule Details
  date: date                            # Date
  startTime: start_time                 # Start Time
  duration: duration                    # Duration - Number (hours)
  location: location                    # Location
  
  # Requirements
  crewRequired: crew_required           # Crew Required - Multi Select
  equipmentRequired: equipment          # Equipment Required - Text Area
  
  # Readiness Tracking
  scenesReadyCount: scenes_ready        # Scenes Ready Count - Number (Automated)
  totalScenesCount: total_scenes        # Total Scenes Count - Number (Automated)
  assetsReady: assets_ready             # Assets Ready - Checkbox (Automated)
  crewConfirmed: crew_confirmed         # Crew Confirmed - Number (0-100%)
  locationConfirmed: location_confirmed  # Location Confirmed - Checkbox
  weatherDependency: weather_dependency  # Weather Dependency - Checkbox
  backupDate: backup_date               # Backup Date
  
  # Automation & Risk
  holdExpires: hold_expires             # Hold Expires - Date (Automated)
  riskLevel: risk_level                 # Risk Level - Single Select (Automated)
  
  # Notes
  notes: notes                          # Notes - Rich Text
  completionNotes: completion_notes     # Completion Notes - Rich Text
  
  # Relationships
  relatedTasks: task_id                 # Related Tasks - Linked Record
  videosAssigned: videos_assigned       # Videos Assigned - Rollup (Count)
  videosReady: videos_ready             # Videos Ready - Rollup (filming_ready = TRUE)
  minimumNeeded: minimum_needed         # Minimum Needed - Number
  
  # Calculated Fields
  goStatus: go_status                   # Go Status - Formula (GO/NO-GO)
  readinessPct: readiness_pct           # Readiness % - Formula

# Booking Type Options
bookingTypeOptions:
  - Recce
  - Shoot
  - Pickups

# Booking Status Options
bookingStatusOptions:
  - Unscheduled
  - Pencilled
  - Confirmed
  - Wrapped
  - Cancelled

# Hold Rank Options
holdRankOptions:
  - 1st
  - 2nd
  - 3rd

# Readiness Status Options
readinessStatusOptions:
  - Go
  - Partially Ready
  - Not Ready

# Crew Required Options
crewRequiredOptions:
  - DoP
  - Sound
  - Gaffer
  - Camera Op
  - Producer
  - Other

# Risk Level Options (Automated)
riskLevelOptions:
  - Low
  - Medium
  - High
  - Critical